import { buildCommand, generateHelpTextForAllCommands } from "@stricli/core";

import type { LocalContext } from "../context.js";

interface HelpFlags {
  readonly full: boolean;
  readonly includeInternal: boolean;
}

/**
 * Render every command's help text as one Markdown document. Each route becomes
 * an `### <route>` section, so the result is readable as a page and greppable as
 * a reference — this is what generates the `claudjar` skill's command reference.
 *
 * The help bodies come from stricli's own renderer, so this document cannot drift
 * from the actual flags: adding a flag changes this output on the next build.
 */
export function renderFullHelp(
  commands: readonly (readonly [string, string])[],
): string {
  const lines: string[] = [
    "# claudjar — full command reference",
    "",
    "Generated by `claudjar help --full`. Do not edit by hand.",
    "",
  ];
  for (const [route, help] of commands) {
    lines.push(`### ${route}`, "", "```", help.trimEnd(), "```", "");
  }
  return lines.join("\n");
}

/**
 * `claudjar help [--full] [--include-internal]`. Bare `claudjar help` points at
 * the built-in flag; `--full` dumps every command's help in one pass.
 *
 * The application is imported lazily because `src/routes.ts` imports this module
 * to register the command — a static import would close the cycle at module load.
 */
async function runHelp(this: LocalContext, flags: HelpFlags): Promise<void> {
  const proc = this.process;

  if (!flags.full) {
    proc.stdout.write(
      "Use `claudjar --help` for the command list, `claudjar <command> --help` " +
        "for one command, or `claudjar help --full` to print them all at once.\n",
    );
    return;
  }

  const { buildDocsApp } = await import("../routes.js");
  // Internals are hidden in the real application, and generateHelpTextForAllCommands
  // skips hidden routes — so including them means walking a second, fully-visible
  // application built from the same route factory.
  const app = buildDocsApp(!flags.includeInternal);
  proc.stdout.write(renderFullHelp(generateHelpTextForAllCommands(app)));
}

export const helpCommand = buildCommand({
  func: runHelp,
  parameters: {
    flags: {
      full: {
        kind: "boolean",
        brief: "Print every command's help text as one Markdown document",
        default: false,
      },
      includeInternal: {
        kind: "boolean",
        brief: "With --full, also include the internal `api` hook commands",
        default: false,
      },
    },
  },
  docs: {
    brief: "Print the full documentation for every command at once",
    fullDescription:
      "`claudjar help --full` renders every command's help into a single Markdown " +
      "document — the same text `--help` shows per command, so it cannot drift " +
      "from the real flags.\n\n" +
      "By default the internal `api` hook commands are omitted, since they are " +
      "invoked by Claude Code rather than by a person. Add --include-internal to " +
      "document those too.",
  },
});
